### ISSUE TITLE
No matching distribution found for setup.py

### ISSUE THREAD

**Issue by swuyts** [phac-nml/mob-suite#1]
Hi there,

I'm running into some trouble with installing the mob-suite.

```
pip install setup.py 
```
```                                                                                                                                              
Collecting setup.py
  Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py
```

What am I doing wrong here? 

Thanks!

**Comment by swuyts** [comment]
I've installed mobsuite as above, but ran into a few other errors:

```
sander@Unif-Antwerpen[AMB-F197] mob_recon --infile AMB-F197.fna --run_typer                                                                                                                         [ 1:23]
Traceback (most recent call last):
  File "/home/sander/miniconda3/bin/mob_recon", line 11, in <module>
    load_entry_point('mob-suite==0.0.1', 'console_scripts', 'mob_recon')()
  File "/home/sander/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sander/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/sander/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/sander/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sander/miniconda3/lib/python3.6/site-packages/mob_suite-0.0.1-py3.6.egg/mob_suite/mob_recon.py", line 237
    os.mkdir(args.outdir, 0755)
                             ^
SyntaxError: invalid token
```

I'm guessing that the code has been written in Python 2 and that this is causing the problems?

Anyway I then tried reinstalling using `python2.7 setup.py install` which failed with the following errors:

```
EOF
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
numpy/core/src/npymath/ieee754.c.src:7:29: fatal error: npy_math_common.h: No such file or directory
 #include "npy_math_common.h"
                             ^
compilation terminated.
numpy/core/src/npymath/ieee754.c.src:7:29: fatal error: npy_math_common.h: No such file or directory
 #include "npy_math_common.h"
                             ^
compilation terminated.
error: Setup script exited with error: Command "x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -I/usr/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -c build/src.linux-x86_64-2.7/numpy/core/src/npymath/ieee754.c -o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/core/src/npymath/ieee754.o -MMD -MF build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/core/src/npymath/ieee754.o.d" failed with exit status 1
```

Any suggestions for what to try next?

**Comment by thanhleviet** [comment]
Looks you have python 3 default. Try to create a virtual env of python 2 using conda, and then reinstall mob-suite again within the new env again.

**Comment by jrober84** [comment]
Hello,

MOB-suite is written in python 2.7, I will be working to port it to 3 fix some of these incompatibilities. I have corrected the documentation for the install.   In the meantime make sure you are using a 2.7 python environment.

% git clone https://github.com/jrober84/mob-suite
% pip install mob-suite/

**Comment by kbessonov1984** [comment]
MOB-suite conda package for python version 3.6 is now available on Anaconda Cloud. Following commands creata a new conda environment and install MOB-suite package and its dependencies for Linux or OSX.

```code
conda create --name mob_suite python=3.6
conda install -c kbessonov mob_suite
```

**Comment by thanhleviet** [comment]
Great! would be nice to have it on bioconda channel

**Comment by jrober84** [comment]
The tool has been added into the Bioconda channel now thanks to the work of kbessonov1984

**Comment by swuyts** [comment]
I was literally just installing it again using @kbessonov1984 commands.

It works perfect now; thanks!
