### ISSUE TITLE
Not clear how to make a custom DB

### ISSUE THREAD

**Issue by iowa69** [phac-nml/mob-suite#112]
How do I make/use a custom DB?

There are some input files that are not specified

% mob_cluster --mode build -f new_plasmids.fasta -p new_plasmids_mobtyper_report.txt -t new_plasmids_host_taxonomy.txt --outdir output_directory

-f new_plasmids.fasta **MY PLASMIDS**
-p new_plasmids_mobtyper_report.txt **MOBTYPER OUTPUT**
-t new_plasmids_host_taxonomy.txt **WHAT IS THIS?**

Then, how do I specify the folder where is the new db created?

Thanks

**Comment by iowa69** [comment]
Thanks for the help,

I have a multi-fasta database (new_database.fasta) with some plasmids in it.

I have formatted the taxonomy file in this way with tab delimited spacer, plasmids are from Klebsiella pneumoniae but cannot figure what to type: (PROBLEM1)

sample_id   organism
NZ_CP070412 Unknown
NZ_CP070417 Unknown
NZ_CP079127 Unknown

after that, using "sample_mobtyper_results.txt" I launched the mob cluster, everything in a desktop folder:

$ mob_cluster --mode build -f new_database1.fasta -p sample_mobtyper_results.txt -t taxonomy.txt --outdir new_databse1 --num_threads 12

I obtain in this case 10 files in the out_dir

clusters.txt
references_updated.fasta
references_updated.fasta.msh
references_updated.fasta.ndb
references_updated.fasta.nhr
references_updated.fasta.nin
references_updated.fasta.not
references_updated.fasta.nsq
references_updated.fasta.ntf
references_updated.fasta.nto

At this point I try to use mob_recon but it does not produce an output: (PROBLEM2)

$ mob_recon -o prova -i KP1057_ST512_KPC-3.fasta -s KP1057 -d new_databse1/

​It re-installs the default ncbi database and it overwrites the clusters.txt file

I then re-specified the two files as described in the issue page but the output did not change, so i substituted in the conda folder the cluster.txt file.

$ mob_recon -n 12 -o prova577c -i KP577_Complete.fasta -s KP577c --plasmid_db new_database/references_updated.fasta --plasmid_mash_db new_database/references_updated.fasta.msh

At this point the output changes but I see that the program assigns contigs that are part of the plasmids (I am checking sequences I know) to chromosome and excludes them. The program is not capable of finishing correctly the analysis.

Is what I have done correct? It is a bit tricky and it is not explained in that way so maybe I am doing something wrong.

Any suggestion on increase accuracy in mob_recon? I can give you my inputs and database if it may help.

Thanks for all,

GL
​

Giovanni Lorenzin, MD

Emerging Bacterial Pathogens Unit

WHO Collaborating Centre in Tuberculosis Laboratory Strengthening - Supranational Reference Laboratory for TB
Div. of Immunology, Transplantation and Infectious Diseases
San Raffaele Scientific Institute
San Gabriele Building
Via Olgettina, 58
20132 Milano, ITALY
Telephone  +39 02 2643 5548
Fax  +39 02 2643 5183



[https://portalepaziente.hsr.it/Natale2019_BannerFirmaMail.jpg]<https://sostienici.hsr.it/sostienici/questo-natale-sostieni-la-ricerca-insieme-a-noi.html>



Rispetta l’ambiente: non stampare questa mail se non è necessario.
Respect the environment: print this email only if necessary.

________________________________

**Comment by iowa69** [comment]
Thanks for the help,

I have a multi-fasta database (new_database.fasta) with some plasmids in it.

I have formatted the taxonomy file in this way with tab delimited spacer, plasmids are from Klebsiella pneumoniae but cannot figure what to type: (PROBLEM1)

sample_id   organism
NZ_CP070412 Unknown
NZ_CP070417 Unknown
NZ_CP079127 Unknown

after that, using "sample_mobtyper_results.txt" I launched the mob cluster, everything in a desktop folder:

$ mob_cluster --mode build -f new_database1.fasta -p sample_mobtyper_results.txt -t taxonomy.txt --outdir new_databse1 --num_threads 12

I obtain in this case 10 files in the out_dir

clusters.txt
references_updated.fasta
references_updated.fasta.msh
references_updated.fasta.ndb
references_updated.fasta.nhr
references_updated.fasta.nin
references_updated.fasta.not
references_updated.fasta.nsq
references_updated.fasta.ntf
references_updated.fasta.nto

At this point I try to use mob_recon but it does not produce an output: (PROBLEM2)

$ mob_recon -o prova -i KP1057_ST512_KPC-3.fasta -s KP1057 -d new_databse1/

​It re-installs the default ncbi database and it overwrites the clusters.txt file

I then re-specified the two files as described in the issue page but the output did not change, so i substituted in the conda folder the cluster.txt file.

$ mob_recon -n 12 -o prova577c -i KP577_Complete.fasta -s KP577c --plasmid_db new_database/references_updated.fasta --plasmid_mash_db new_database/references_updated.fasta.msh

At this point the output changes but I see that the program assigns contigs that are part of the plasmids (I am checking sequences I know) to chromosome and excludes them. The program is not capable of finishing correctly the analysis.

Is what I have done correct? It is a bit tricky and it is not explained in that way so maybe I am doing something wrong.

Any suggestion on increase accuracy in mob_recon? I can give you my inputs and database if it may help.

Thanks for all,

GL

**Comment by kbessonov1984** [comment]
Good day,
Indeed there are small practical aspects that need to be clarified as mob-cluster is scarcely documented as it was more designed for an internal use.
The plasmid database building command is correct and generated all necessary files. The most important files are `references_updated.fasta`, mash sketch of it `references_updated.fasta.msh`
it `references_updated.fasta.msh` and `clusters.txt` containing all metadata on your plasmid sequences. Also remember that MOB-suite uses numerous databases including database on replicon, relaxases, repetitive elements and others. In your use case you just want to swap the plasmid database for a new one and leave all other databases intact. The `mob_recon` command that you've specified need additional argument specified `--plasmid_meta` pointing to the new `clusters.txt` file from your custom database (i.e. `--plasmid_meta new_database/clusters.txt`).

By default a given contig is assigned to `plasmid` molecule type if it is a member of a known `primary_cluster_id` MOB-plasmid cluster defined in `cluster.txt` and supported by a MASH distance lower or equal to 0.06. In addition presence of relaxase and replicon sequences on a contig and no membership to a known MOB-cluster should also result in a given contig to be classified of `plasmid` type. Another criteria include presence of repetitive elements and contig circularity status (i.e. contigs marked as circular by `unicycler` assembler or that could be circularized). Finally, the is optional `--genome_filter_db_prefix` argument that one could specify path to reference genomes of closed genomes that will filter out problematic chromosomal sequences improving plasmid predation especially for chromosomally integrated plasmids.

I am curious why you've got your expected contigs specified as chromosomal and not plasmid. Do they have any replicon and relaxases sequences on them. Check by BLAST against the `rep.dna.fas` and `mob.proteins.faa` databases or check the mob-typer output for the respective columns.

Have you BLAST them and got plasmid hits? 
What results do you get when using a default database? 
Your known plasmid contigs are also classified as chromosomal by running the default database or only your custom one? 
It might take longer, but you can also add your sequences to an existing plasmid database and see what results you get.

The database initialization routine is triggered if the `--database_directory` parameter is specified and a new folder does not contain the `status.txt` file triggering the `mob_init` routine with all databases initialization coupled to a long taxonomy initialization for the ETE3 library (stored in `taxa.sql`) to support host-range module predictions.

**Comment by cizydorczyk** [comment]
I keep getting the following error when trying to set up my own db:

```
...
2024-10-22 09:53:34,713 root INFO: SUCCESS: Found program tblastn at /usr/bin/tblastn [in /home/user/miniconda3/envs/mobsuite-env/lib/python3.8/site-packages/mob_suite/utils.py:597]
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mobsuite-env/bin/mob_cluster", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/mobsuite-env/lib/python3.8/site-packages/mob_suite/mob_cluster.py", line 540, in main
    organism = new_seq_info[seq_id]['organism']
KeyError: 'organism'
```

Tax file looks like:

```
sample_id	organism
PP320245	Unknown
...
```

Plasmids are simply named according to the sample_id in the tax file. I ran mob_typer on the plasmids no problem.

Any suggestions?

**Comment by Rikkiff** [comment]
Hi, 
I am attempting to add a handful of sequences to the ncbi_plasmid_full_seqs.fas file. I have appended my sequences and ran the following code as adviced: 
mob_cluster -m build -i ncbi_plasmid_full_seqs.fas --num_threads 3 -o newdb

However, I get the following error message:
mob_cluster: error: the following arguments are required: -f/--infile, -p/--mob_typer_file, -t/--taxonomy

From the above discussion I can understand that -t takes a taxonomy file an accession and host organism. But should I replace the -i option in the command with --infile option? Also, I don't understand where I should get the mob_typer_file from? In the discussion above "-p sample_mobtyper_results.txt" is used. Is this a default file I can also use, or was it specifically created by the user? 

Best, 
Rikki
