### ISSUE TITLE
Error Installing mob suite from conda 

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [phac-nml/mob-suite#119]
Hi, I tried to install MOB SUITE. I got the error.

Here is the traceback.

```
conda install -c bioconda mob_suite
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/yichen/anaconda3

  added / updated specs:
    - mob_suite


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blast-2.12.0               | pl5262h3289130_0        22.4 MB  bioconda
    capnproto-0.6.1            |       hfc679d8_1         2.7 MB  conda-forge
    conda-build-3.22.0         |   py39hf3d152e_2         563 KB  conda-forge
    entrez-direct-16.2         |       he881be0_1         7.5 MB  bioconda
    ete3-3.1.2                 |     pyh9f0ad1d_0         1.8 MB  conda-forge
    gsl-1.16                   |                0         6.9 MB  conda-forge
    mash-2.0                   |        gsl1.16_1         223 KB  bioconda
    mob_suite-3.0.0            |             py_1         184 KB  bioconda
    patch-2.7.6                |    h7f98852_1002         121 KB  conda-forge
    perl-5.26.2                |    h36c2ea0_1008        15.4 MB  conda-forge
    perl-archive-tar-2.18      |                1          27 KB  bioconda
    perl-common-sense-3.74     |          pl526_2          11 KB  bioconda
    perl-json-4.02             |          pl526_0          52 KB  bioconda
    perl-json-xs-2.34          |          pl526_1          61 KB  bioconda
    perl-list-moreutils-0.15   |          pl526_1          13 KB  bioconda
    xorg-libsm-1.2.2           |       h470a237_5          24 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        57.9 MB

The following NEW packages will be INSTALLED:

  blast              bioconda/linux-64::blast-2.12.0-pl5262h3289130_0
  capnproto          conda-forge/linux-64::capnproto-0.6.1-hfc679d8_1
  entrez-direct      bioconda/linux-64::entrez-direct-16.2-he881be0_1
  ete3               conda-forge/noarch::ete3-3.1.2-pyh9f0ad1d_0
  gsl                conda-forge/linux-64::gsl-1.16-0
  libgcc             conda-forge/linux-64::libgcc-7.2.0-h69d50b8_2
  mash               bioconda/linux-64::mash-2.0-gsl1.16_1
  mob_suite          bioconda/noarch::mob_suite-3.0.0-py_1
  patch              conda-forge/linux-64::patch-2.7.6-h7f98852_1002
  perl               conda-forge/linux-64::perl-5.26.2-h36c2ea0_1008
  perl-archive-tar   bioconda/linux-64::perl-archive-tar-2.18-1
  perl-common-sense  bioconda/linux-64::perl-common-sense-3.74-pl526_2
  perl-json          bioconda/linux-64::perl-json-4.02-pl526_0
  perl-json-xs       bioconda/linux-64::perl-json-xs-2.34-pl526_1
  perl-list-moreuti~ bioconda/linux-64::perl-list-moreutils-0.15-pl526_1
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h7f98852_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.2-h470a237_5
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.7.2-h7f98852_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h7f98852_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h7f98852_1
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h7f98852_1003
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h7f98852_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h7f98852_1007

The following packages will be UPDATED:

  conda-build        pkgs/main::conda-build-3.21.5-py39h06~ --> conda-forge::conda-build-3.22.0-py39hf3d152e_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
entrez-direct-16.2   | 7.5 MB    | ##################################### | 100% 
conda-build-3.22.0   | 563 KB    | ##################################### | 100% 
mob_suite-3.0.0      | 184 KB    | ##################################### | 100% 
xorg-libsm-1.2.2     | 24 KB     | ##################################### | 100% 
perl-5.26.2          | 15.4 MB   | ##################################### | 100% 
blast-2.12.0         | 22.4 MB   | ##################################### | 100% 
capnproto-0.6.1      | 2.7 MB    | ##################################### | 100% 
perl-json-4.02       | 52 KB     | ##################################### | 100% 
perl-list-moreutils- | 13 KB     | ##################################### | 100% 
perl-common-sense-3. | 11 KB     | ##################################### | 100% 
gsl-1.16             | 6.9 MB    | ##################################### | 100% 
mash-2.0             | 223 KB    | ##################################### | 100% 
perl-archive-tar-2.1 | 27 KB     | ##################################### | 100% 
perl-json-xs-2.34    | 61 KB     | ##################################### | 100% 
ete3-3.1.2           | 1.8 MB    | ##################################### | 100% 
patch-2.7.6          | 121 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'bioconda::mob_suite-3.0.0-py_1'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::mob_suite-3.0.0-py_1
location of failed script: /home/yichen/anaconda3/bin/.mob_suite-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/yichen/anaconda3/bin/mob_init", line 7, in <module>
    from mob_suite.mob_init import main
  File "/home/yichen/anaconda3/lib/python3.9/site-packages/mob_suite/mob_init.py", line 8, in <module>
    from mob_suite.blast import BlastRunner
  File "/home/yichen/anaconda3/lib/python3.9/site-packages/mob_suite/blast/__init__.py", line 9, in <module>
    from pandas.io.common import EmptyDataError
ImportError: cannot import name 'EmptyDataError' from 'pandas.io.common' (/home/yichen/anaconda3/lib/python3.9/site-packages/pandas/io/common.py)

return code: 1

()
```

**Comment by kbessonov1984** [comment]
Hi, you are installing version of MOB-Suite that had no restriction to `pandas` version upper bound. You can simply install `conda install pandas==1.0.5` and then install mob-suite again.

**Comment by jrober84** [comment]
I am marking this as closed for now

**Comment by gilmahu** [comment]
Dear @kbessonov1984
Unfortunately, installation through conda still contains only the old version 3.0.0. 

When i try forcing new versions 3.0.3. or 3.1.0 in with conda it comes out with error: 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
