### ISSUE TITLE
Minimum Biopython version?

### ISSUE THREAD

**Issue by cmfield** [phac-nml/mob-suite#134]
Running any part of mob-suite I get this error:

```Traceback (most recent call last):
  File "/nfs/nas22/fs2201/biol_micro_unix_modules/modules/software/MOB-Suite/3.1.4-foss-2020b/bin/mob_init", line 5, in <module>
    from mob_suite.mob_init import main
  File "/nfs/nas22/fs2201/biol_micro_unix_modules/modules/software/MOB-Suite/3.1.4-foss-2020b/lib/python3.8/site-packages/mob_suite/mob_init.py", line 13, in <module>
    from mob_suite.utils import init_console_logger
  File "/nfs/nas22/fs2201/biol_micro_unix_modules/modules/software/MOB-Suite/3.1.4-foss-2020b/lib/python3.8/site-packages/mob_suite/utils.py", line 2, in <module>
    from Bio.SeqUtils import gc_fraction
ImportError: cannot import name 'gc_fraction' from 'Bio.SeqUtils' (/nfs/nas22/fs2201/biol_micro_unix_modules/modules/software/Biopython/1.78-foss-2020b/lib/python3.8/site-packages/Bio/SeqUtils/__init__.py)
```

I believe this is because gc_fraction wasn't introduced until Biopython 1.8? Certainly I can't find it in any earlier version.

**Comment by uyghbo** [comment]
I also encountered this problem.

**Comment by jrober84** [comment]
The requirements have been updated to require >= biopython 1.8
