### ISSUE TITLE
TypeError: hostrange() missing 1 required positional argument: 'database_directory'

### ISSUE THREAD

**Issue by Longyulin22** [phac-nml/mob-suite#162]
Thank you for such a good software，but I've come across some kus while using it
first，I installed it by conda;then,I  ordered mob_init to download the databases;finally,I started to work,but it has some errors like TypeError: hostrange() missing 1 required positional argument: 'database_directory'
my log:mob_recon -i 120.fasta -o mob_suite_output/120 -s 120 -n 24 -d /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/databases
2024-05-10 15:19:22,456 mob_suite.mob_recon INFO: MOB-recon version 3.1.5  [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:980]
2024-05-10 15:19:22,456 mob_suite.mob_recon INFO: SUCCESS: Found program blastn at /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/bin/blastn [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:592]
2024-05-10 15:19:22,456 mob_suite.mob_recon INFO: SUCCESS: Found program makeblastdb at /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/bin/makeblastdb [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:592]
2024-05-10 15:19:22,456 mob_suite.mob_recon INFO: SUCCESS: Found program tblastn at /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/bin/tblastn [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:592]
2024-05-10 15:19:22,456 mob_suite.mob_recon INFO: Processing fasta file 120.fasta [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:1007]
2024-05-10 15:19:22,456 mob_suite.mob_recon INFO: Analysis directory mob_suite_output/120 [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:1008]
2024-05-10 15:19:29,190 mob_suite.mob_recon INFO: Writing cleaned header input fasta file from 120.fasta to mob_suite_output/120/__tmp/fixed.input.fasta [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:1103]
2024-05-10 15:19:29,447 root INFO: Blasting replicon sequences /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/databases/rep.dna.fas against mob_suite_output/120/__tmp/fixed.input.fasta [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1150]
2024-05-10 15:19:30,203 root INFO: Filtering replicon blast results mob_suite_output/120/__tmp/replicon_blast_results.txt  [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1155]
2024-05-10 15:19:30,230 root INFO: Blasting relaxase sequences /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/databases/mob.proteins.faa against mob_suite_output/120/__tmp/fixed.input.fasta [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1173]
2024-05-10 15:19:33,799 root INFO: Filtering relaxase blast results mob_suite_output/120/__tmp/mob_blast_results.txt  [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1178]
2024-05-10 15:19:33,816 root INFO: Blasting MPF sequences /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/databases/mpf.proteins.faa against mob_suite_output/120/__tmp/fixed.input.fasta [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1197]
2024-05-10 15:19:36,200 root INFO: Filtering MPF blast results mob_suite_output/120/__tmp/mpf_blast_results.txt  [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1212]
2024-05-10 15:19:36,202 root INFO: Blasting orit sequences /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/databases/orit.fas against mob_suite_output/120/__tmp/fixed.input.fasta [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1221]
2024-05-10 15:19:36,425 root INFO: Filtering orit blast results mob_suite_output/120/__tmp/orit_blast_results.txt  [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1226]
2024-05-10 15:19:36,440 root INFO: Blasting contigs against repetitive sequences db: /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/databases/repetitive.dna.fas [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1243]
2024-05-10 15:19:37,290 root INFO: Filtering repetitive blast results mob_suite_output/120/__tmp/repetitive_blast_results.txt  [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1247]
2024-05-10 15:19:37,299 root INFO: Filtering contig: 21_043b3c57b370f26cde2879d10b69016c_circular=false due to repetitive sequence [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1262]
2024-05-10 15:19:37,299 root INFO: Filtering contig: 20_02c7aca29e7a3dedd91ea5c5076f8287_circular=false due to repetitive sequence [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:1262]
2024-05-10 15:19:37,299 root INFO: Blasting contigs against reference sequence db: /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/databases/ncbi_plasmid_full_seqs.fas [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:1260]
2024-05-10 15:19:45,001 root INFO: Filtering contig blast results: mob_suite_output/120/__tmp/contig_blast_results.txt [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:1265]
2024-05-10 15:19:45,250 root INFO: Assigning contigs to plasmid groups [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:1280]
2024-05-10 15:19:48,165 root INFO: Writting contig results to mob_suite_output/120/contig_report.txt [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py:1382]
2024-05-10 15:19:52,710 root INFO: Writting plasmid sequences to mob_suite_output/120/plasmid_AB461.fasta [in /ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py:957]
Traceback (most recent call last):
  File "/ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/bin/mob_recon", line 10, in <module>
    sys.exit(main())
  File "/ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/mob_recon.py", line 1395, in main
    build_mobtyper_report(contig_memberships['plasmid'], out_dir, mobtyper_report,contig_seqs, ncbi, lit,ETE3DBTAXAFILE)
  File "/ifs1/User/longyulin/mambaforge-pypy3/envs/mob_suite/lib/python3.8/site-packages/mob_suite/utils.py", line 1067, in build_mobtyper_report
    host_range = hostrange(rep_types, relaxase_types, mob_cluster_id, ncbi, lit,ETE3DBTAXAFILE)
TypeError: hostrange() missing 1 required positional argument: 'database_directory'

**Comment by kbessonov1984** [comment]
Try to update to the most recent version of the MOB-Suite which is 3.1.8 that has this issue resolved and make sure your ETE3 version is >= 3.1.3. Looks like you are running MOB-Suite version 3.1.5.
