### ISSUE TITLE
mob_typer import error

### ISSUE THREAD

**Issue by anatori** [phac-nml/mob-suite#25]
I have issues running mob_typer. When I enter:
`mob_typer --infile myassembly.fasta --outdir my_out_dir`

The error message comes up as:
```
Traceback (most recent call last):
  File "/home/ana/anaconda3/bin/mob_typer", line 11, in <module>
    load_entry_point('mob-suite==2.0.0', 'console_scripts', 'mob_typer')()
  File "/home/ana/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ana/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/ana/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/ana/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ana/anaconda3/lib/python3.7/site-packages/mob_suite-2.0.0-py3.7.egg/mob_suite/mob_typer.py", line 28, in <module>
    from mob_suite.mob_host_range import getTaxonomyTree, getLiteratureBasedHostRange, loadliteratureplasmidDB, \
  File "/home/ana/anaconda3/lib/python3.7/site-packages/mob_suite-2.0.0-py3.7.egg/mob_suite/mob_host_range.py", line 9, in <module>
    from ete3 import NCBITaxa, TreeStyle
ImportError: cannot import name 'TreeStyle' from 'ete3' (/home/ana/anaconda3/lib/python3.7/site-packages/ete3-3.1.1-py3.7.egg/ete3/__init__.py)
```
I'm not sure what's particularly the issue and how to go about this.

Thanks,
Ana

**Comment by kbessonov1984** [comment]
Hi Ana,
The error is linked to the `ete3` module which can not import `TreeStyle` submodule. I've also had similar issues with the `ete3` module used to run host range predictions. The solution is to re-install `ete3` module and make sure you also have installed `qt` library for image rendering (e.g. `https://anaconda.org/conda-forge/qt`)

Alternatively try to install new conda package which has all dependencies installed by running the following command in your conda environment
`conda install -c kbessonov mob_suite`

Let us know if you have any success

**Comment by anatori** [comment]
I tried the second option first and it worked immediately. Thank you so much!

**Comment by kbessonov1984** [comment]
That is great to hear and thank you for reporting an issue. Sorry for inconvenience. The best way to install `mob_suite` is via conda right now due to large list of package dependencies. We are still trying to test the new `ete3` module for potential tree rendering issues before releasing the final bioconda recipe.
