### ISSUE TITLE
MOB-host range module error in mean transfer rate

### ISSUE THREAD

**Issue by jrober84** [phac-nml/mob-suite#41]
When a plasmid matches a set of literature with a mixture of transfer rates and no transfer rates, then any numerical operations on the list will cause the program to fail. I have added numerical checking to mean. as well as a filter to literature_knowledge["TransferRate"] to only have numerical values. This is addressed in commits: 69b833d..85fdf75 .

Traceback (most recent call last):

  File "/home/brovervv/miniconda3/envs/mob_suite/lib/python3.6/site-packages/mob_suite/mob_typer.py", line 514, in <module>

    main()

  File "/home/brovervv/miniconda3/envs/mob_suite/lib/python3.6/site-packages/mob_suite/mob_typer.py", line 395, in main

    literature_hr_report=host_range_literature_report_df)

  File "/home/brovervv/miniconda3/envs/mob_suite/lib/python3.6/site-packages/mob_suite/mob_host_range.py", line 612, in writeOutHostRangeReports

    literature_hr_report = collapseLiteratureReport(literature_hr_report) #collapse report

  File "/home/brovervv/miniconda3/envs/mob_suite/lib/python3.6/site-packages/mob_suite/mob_host_range.py", line 309, in collapseLiteratureReport

    collapsedlitdf.loc[0,field] = mean(df[df[field].isna() == False][field].values)

  File "/home/brovervv/miniconda3/envs/mob_suite/lib/python3.6/site-packages/mob_suite/mob_host_range.py", line 342, in mean

    return float(sum(numbers)) / max(len(numbers), 1)

TypeError: unsupported operand type(s) for +: 'float' and 'str'

**Comment by kbessonov1984** [comment]
Thank you for fixing this bug in a double KO way! I like that there are 2 checks both at the level of the transfer rate values and mean calculation itself. Thank you for spotting this issue.

The first check will only add to the transfer rate array int and float values
```
temp = []
for r in literature_knowledge["TransferRate"]:
            if isinstance(r,int) or isinstance(r,float):
                temp.append(r)
        literature_knowledge["TransferRate"] = temp
```

The mean function will return "N/A" if array is empty or non-numeric. After the 1st check I do not see this happening, but still good to have this case check.
```
def mean(numbers):
    if not isinstance(numbers,int) and not isinstance(numbers,float):
        mean = 'N/A'
    else:
        mean = float(sum(numbers)) / max(len(numbers), 1)
    return mean 
```
Again, nice cause to create another test function covering this case.
