### ISSUE TITLE
Lock file is created in /usr/local/ though the database is in a different directory

### ISSUE THREAD

**Issue by vbrover** [phac-nml/mob-suite#93]
```
$ /usr/local/mob-suite/3.0.3/bin/mob_recon --infile skesa/SRR7653407  --outdir SRR7653407.mob_recon  -n 16 --database_directory /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/home/brovervv/PD-plasmid/mob.data 
2021-10-07 10:29:29,427 mob_suite.mob_recon INFO: MOB-recon version 3.0.2  [in /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/mob_recon.py:983]
2021-10-07 10:29:29,457 mob_suite.mob_recon INFO: SUCCESS: Found program blastn at /usr/bin/blastn [in /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/utils.py:571]
2021-10-07 10:29:29,457 mob_suite.mob_recon INFO: SUCCESS: Found program makeblastdb at /usr/bin/makeblastdb [in /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/utils.py:571]
2021-10-07 10:29:29,458 mob_suite.mob_recon INFO: SUCCESS: Found program tblastn at /usr/bin/tblastn [in /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/utils.py:571]
2021-10-07 10:29:29,459 mob_suite.mob_recon INFO: Processing fasta file skesa/SRR7653407 [in /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/mob_recon.py:1004]
2021-10-07 10:29:29,459 mob_suite.mob_recon INFO: Analysis directory SRR7653407.mob_recon [in /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/mob_recon.py:1005]
2021-10-07 10:29:29,470 root INFO: Creating Lock file /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/databases/ETE3_DB.lock [in /usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/utils.py:438]
Traceback (most recent call last):
  File "/usr/local/mob-suite/3.0.3/bin/mob_recon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/mob_recon.py", line 1096, in main
    dbstatus = ETE3_db_status_check(1, ETE3_LOCK_FILE, ETE3DBTAXAFILE, logging)
  File "/usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/utils.py", line 439, in ETE3_db_status_check
    open(file=lockfilepath, mode="w").close()
OSError: [Errno 30] Read-only file system: '/usr/local/mob-suite/3.0.3/lib/python3.9/site-packages/mob_suite/databases/ETE3_DB.lock'
```

**Comment by jrober84** [comment]
The issue is that ETE3 will trigger its own update if it detects there has been a change in the NCBI database. I have removed the locking mechanism from the new pending release but there is a risk to cascade multiple attempts to update the ncbi taxonomy database
