### ISSUE TITLE
mob init: File not found on server

### ISSUE THREAD

**Issue by nick-youngblut** [phac-nml/mob-suite#98]
Installing mob-suite via conda results in the following error:

```
[...]
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading Resfam database

Downloading Resfams.hmm.gz:  5.48% downloaded.
Downloading Resfams.hmm.gz: 10.95% downloaded.
Downloading Resfams.hmm.gz: 16.43% downloaded.
Downloading Resfams.hmm.gz: 21.90% downloaded.
Downloading Resfams.hmm.gz: 27.38% downloaded.
Downloading Resfams.hmm.gz: 32.86% downloaded.
Downloading Resfams.hmm.gz: 38.33% downloaded.
Downloading Resfams.hmm.gz: 43.81% downloaded.
Downloading Resfams.hmm.gz: 49.28% downloaded.
Downloading Resfams.hmm.gz: 54.76% downloaded.
Downloading Resfams.hmm.gz: 60.24% downloaded.
Downloading Resfams.hmm.gz: 65.71% downloaded.
Downloading Resfams.hmm.gz: 71.19% downloaded.
Downloading Resfams.hmm.gz: 76.66% downloaded.
Downloading Resfams.hmm.gz: 82.14% downloaded.
Downloading Resfams.hmm.gz: 87.62% downloaded.
Downloading Resfams.hmm.gz: 93.09% downloaded.
Downloading Resfams.hmm.gz: 98.57% downloaded.
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Ensuring all cutoffs are present
Downloading ClusterBlast database.

stderr: /tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/download_databases.py", line 82, in download_file
    req = request.urlopen(url)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/bin/download-antismash-databases", line 10, in <module>
    sys.exit(_main())
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/download_databases.py", line 352, in _main
    download(args)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/download_databases.py", line 330, in download
    download_clusterblast(args.database_dir)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/download_databases.py", line 307, in download_clusterblast
    download_if_not_present(CLUSTERBLAST_URL, archive_filename, CLUSTERBLAST_ARCHIVE_CHECKSUM)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/download_databases.py", line 207, in download_if_not_present
    download_file(url, filename)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/download_databases.py", line 84, in download_file
    raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
antismash.download_databases.DownloadError: ERROR: File not found on server.
Please check your internet connection.

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/condabin/mamba", line 11, in <module>
    sys.exit(main())
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/mamba/mamba.py", line 886, in main
    return mamba_env.main()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/mamba/mamba_env.py", line 141, in main
    return conda_env_main()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda_env/cli/main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/exceptions.py", line 1113, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/exceptions.py", line 1056, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/logging/__init__.py", line 1523, in handle
    if (not self.disabled) and self.filter(record):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/logging/__init__.py", line 751, in filter
    result = f.filter(record)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/gateways/logging.py", line 60, in filter
    record.msg = record.msg % new_args
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/__init__.py", line 126, in __repr__
    errs.append(e.__repr__())
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/__init__.py", line 65, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.7/site-packages/conda/__init__.py", line 84, in __str__
    return text_type(self.message % self._kwargs)
TypeError: %d format: a number is required, not dict
```

Although I get a `Please check your internet connection.` error, there is no issue with the internet connection, especially given that the Resfam database  downloaded successfully

**Comment by nick-youngblut** [comment]
Sorry for the confusing post, this error is actually an antismash issue
